SELECT TOP (1000) [SaleID]
      ,[DateID]
      ,[CustomerID]
      ,[ProductID]
      ,[SupplierID]
      ,[LocationID]
      ,[Quantity]
      ,[TotalAmount]
  FROM [Poultry_1].[dbo].[Poultry_Sales_Fact]
